app = "qdrant"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "storage"
  destination = "/qdrant/storage"

[[services]]
  protocol = "tcp"
  internal_port = 6333
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 6333
    handlers = ["http", "tls"]
    force_https = false

[[services]]
  protocol = "tcp"
  internal_port = 6334
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 6334
    handlers = ["http"]
    force_https = false

[[services]]
  protocol = "tcp"
  internal_port = 6335
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 6335
    handlers = ["http"]
    force_https = false

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20