app = "vector"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8686
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.http_check]
    port = 8686
    grace_period = "30s"
    interval = "15s"
    method = "get"
    timeout = "10s"
    type = "http"
